/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package numereprime_swingworker;

import java.util.List;
import java.util.concurrent.ExecutionException;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.SwingWorker;

class GeneratorNumerePrime extends SwingWorker<Integer , Integer> 
{
    int max;
    JTextArea nrPrime;

    public GeneratorNumerePrime(int max, JTextArea nrPrime)
    {
        this.max = max;
        this.nrPrime = nrPrime;
    }
    
    //aici se implementeaza "firul de executare"
    protected Integer doInBackground()
    {
        int d , i , k;
        
        k = 0;
        for(i = 2; (i <= max) && (isCancelled() == false); i++)
        {
            boolean prim = true;
            for(d = 2; (d <= i/2) && (prim == true); d++)
                if(i % d == 0)
                    prim = false;
            
            if(prim == true)
            {
                //"se publica" un numar prim
                publish(i);
                k++;
            }
        }
        
        //numarul de nr. prime generate
        return k;
    }
    
    //in lista se gasesc toate numerele "publicate"
    protected void process(List<Integer> prime) 
    {
        for(Integer p : prime)
            nrPrime.append(p + "\n");
    }
    
    public void done()
    {
        try 
        {
            if(isCancelled() == false)
                JOptionPane.showMessageDialog(null , "Au fost generate " + get() + " de numere prime!" , "Numere prime", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(null , "Generatorul de numere prime a fost intrerupt!" , "Numere prime", JOptionPane.INFORMATION_MESSAGE);
        } 
        catch (InterruptedException ex) 
        {
            JOptionPane.showMessageDialog(null , "Generatorul de numere prime a fost intrerupt!" , "Numere prime", JOptionPane.INFORMATION_MESSAGE);
        } 
        catch (ExecutionException ex) {
            JOptionPane.showMessageDialog(null , "A aparut o eroare in generator!" , "Numere prime", JOptionPane.INFORMATION_MESSAGE);
        }
   }
}

public class NumerePrime extends javax.swing.JFrame
{
    GeneratorNumerePrime g;
    
    public NumerePrime()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        ValoareMaxima = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextPrime = new javax.swing.JTextArea();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Numere prime");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Valoarea maximă:");
        jLabel1.setAlignmentX(0.5F);
        getContentPane().add(jLabel1);

        ValoareMaxima.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ValoareMaxima.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ValoareMaxima.setToolTipText("");
        ValoareMaxima.setMaximumSize(new java.awt.Dimension(100, 30));
        ValoareMaxima.setMinimumSize(new java.awt.Dimension(100, 30));
        ValoareMaxima.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(ValoareMaxima);
        getContentPane().add(filler1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Numere prime:");
        jLabel2.setAlignmentX(0.5F);
        getContentPane().add(jLabel2);

        TextPrime.setColumns(20);
        TextPrime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextPrime.setRows(5);
        jScrollPane1.setViewportView(TextPrime);

        getContentPane().add(jScrollPane1);
        getContentPane().add(filler2);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Start");
        jButton1.setAlignmentX(0.5F);
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Stop");
        jButton2.setAlignmentX(0.5F);
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        TextPrime.setText("");
        g = new GeneratorNumerePrime(Integer.parseInt(ValoareMaxima.getText()) , TextPrime);
        g.execute();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        g.cancel(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Metal".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(NumerePrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(NumerePrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(NumerePrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(NumerePrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new NumerePrime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextPrime;
    private javax.swing.JTextField ValoareMaxima;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
